import type { Fixture } from "./types";

export const MOCK_FIXTURES: Fixture[] = [
  {
    id: 1,
    event: 1,
    kickoff_time: "2026-08-22T14:00:00",
    finished: false,
    team_h_id: 1,
    team_a_id: 15,
    team_h_name: "Arsenal",
    team_a_name: "Man City",
    team_h_short: "ARS",
    team_a_short: "MCI",
    team_h_score: null,
    team_a_score: null,
    team_h_difficulty: 4,
    team_a_difficulty: 3,
  },
  {
    id: 2,
    event: 1,
    kickoff_time: "2026-08-22T16:30:00",
    finished: false,
    team_h_id: 16,
    team_a_id: 12,
    team_h_name: "Man Utd",
    team_a_name: "Liverpool",
    team_h_short: "MUN",
    team_a_short: "LIV",
    team_h_score: null,
    team_a_score: null,
    team_h_difficulty: 4,
    team_a_difficulty: 3,
  },
  {
    id: 3,
    event: 1,
    kickoff_time: "2026-08-23T13:00:00",
    finished: false,
    team_h_id: 6,
    team_a_id: 8,
    team_h_name: "Chelsea",
    team_a_name: "Brighton",
    team_h_short: "CHE",
    team_a_short: "BHA",
    team_h_score: null,
    team_a_score: null,
    team_h_difficulty: 2,
    team_a_difficulty: 3,
  },
  {
    id: 4,
    event: 1,
    kickoff_time: "2026-08-23T15:30:00",
    finished: false,
    team_h_id: 2,
    team_a_id: 18,
    team_h_name: "Aston Villa",
    team_a_name: "Newcastle",
    team_h_short: "AVL",
    team_a_short: "NEW",
    team_h_score: null,
    team_a_score: null,
    team_h_difficulty: 3,
    team_a_difficulty: 3,
  },
];
